apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 3000 # this port is accessible to other pods
      targetPort: 80 # if sb comes via 3000 on pod, redirect to 80
      # nodePort: 32323 # outside port 
#  type: NodePort # stick with ClusterIP